/*************************************************************************
  This file generated by gatekeeper, the redshift permissions management tool
  and should not be manually tampered with in any way.
    user name: {{user.name}}
**************************************************************************/

-- create user
CREATE USER {{user.name}} WITH PASSWORD '{xxx-placeholder-xxx}'
{%if user.create_db%}CREATEDB{%else%}NOCREATEDB{%endif%}

{%if user.create_user%}CREATEUSER{%else%}NOCREATEUSER{%endif%}

SYSLOG ACCESS {{user.sys_log_access}}
{%if user.temporary%}VALID UNTIL '{{user.valid_until}}'{%endif%}
CONNECTION LIMIT {{user.connection_limit}}
;
