/*************************************************************************
  This file generated by gatekeeper, the redshift permissions management tool
    user name: {{users}}
**************************************************************************/

-- remove this user from all groups regardless of membership.
{% for group in db_groups %}
ALTER GROUP {{group.name}} DROP USER {{users}};
{%endfor%}

-- revoke all access from all objects in the database.
{% for schema in schemas %}
-- remove access for {{schema.name}} / {{users}}
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA {{schema.name}} FROM {{users}};
REVOKE ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA {{schema.name}} FROM {{users}};

{%endfor%}

DROP USER {{users}};


