/*************************************************************************
  This file generated by gatekeeper, the redshift permissions management tool
    group name: {{group.name}}
**************************************************************************/

CREATE GROUP {{group.name}};

-- granting usage access to group {{group.name}}
GRANT USAGE ON SCHEMA {{group.schema}} TO GROUP {{group.name}};


-- granting object access
{%if group.kind == 'full'%}
GRANT ALL PRIVILEGES ON ALL {{group.access.upper()}} IN SCHEMA {{group.schema}} TO GROUP {{group.name}};
{%endif%}
{%if group.kind == 'limited_read' and group.access in ['tables', 'views']%}
{% for name in group.names %}
GRANT SELECT ON {{group.schema}}.{{name}} TO GROUP {{group.name}};
{%endfor%}
{%endif%}
{%if group.kind == 'limited_write' and group.access in ['tables', 'views']%}
{% for name in group.names %}
GRANT SELECT, INSERT, UPDATE, DELETE ON {{group.schema}}.{{name}} TO GROUP {{group.name}};
{%endfor%}
{%endif%}
