/*************************************************************************
  This file generated by gatekeeper, the redshift permissions management tool
    user name: {{user.name}}
**************************************************************************/


-- create user
CREATE USER {{user.name}};

{%if user.groups%}
-- add the user {{user.name}} to its assigned groups through the role association.
{%for group in user.groups%}
ALTER GROUP {{group.name}} ADD USER {{user.name}};
{%endfor%}
{%endif%}
